### ISSUE TITLE
Button to "send me this message"

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/mailarchive#1070]
`owner:rcross@amsl.com` `type_enhancement`   |    by barryleiba@computer.org

___

When I'm viewing a message in the archive, it would be very helpful to have a button to "send me this message", which would cause the message to be emailed to the logged-in user, just as it was originally posted.  If one is going to reply to a posting, it's hard to do that just from the archive, and still retain all the threading context and such.  Being able to get the message into one's email stream would fix that.

(IMAP access will fix that also, but this feature will be useful for people who can't or don't want to use IMAP.)

___
_Issue migrated from trac:1070 at 2022-03-03 01:35:41 +0000_

**Comment by rpcross** [comment]
Duplicate of issue #3852

**Comment by Asrcreateofficial** [comment]
`owner:rcross@amsl.com` `type_enhancement`   |    by barryleiba@computer.org

___


When I'm viewing a message in the archive, it would be very helpful to have a button to "send me this message", which would cause the message to be emailed to the logged-in user, just as it was originally posted.  If one is going to reply to a posting, it's hard to do that just from the archive, and still retain all the threading context and such.  Being able to get the message into one's email stream would fix that.

(IMAP access will fix that also, but this feature will be useful for people who can't or don't want to use IMAP.)

___
_Issue migrated from trac:1070 at 2022-03-03 01:35:41 +0000_
