### ISSUE TITLE
Create data export API

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/mailarchive#2488]
`owner:rcross@amsl.com` `type_enhancement`   |    by rcross@amsl.com

___

Need a data export API for providing an external reporting tools, dashboard, with mailing list data.  See IMR Reports "lists" and "subcounts" reports for example.

___
_Issue migrated from trac:2488 at 2022-03-03 10:01:19 +0000_

**Comment by rpcross** [comment]
API Data (suggested by Robert 10-2021)

At some point, we should talk about either extending the api endpoint you've already started, or adding another one, that will answer questions like this one easily. Other variants would be "What lists and how many messages did <foo> post to last week".

Messages from the ietf list for the week ending Sun Oct 10 06:00:20 2021

Count | Bytes | Who
------------+----------------+-------
76 ( 100%) | 623655 ( 100%) | Total
10 (13.2%) | 85410 (13.7%) | Salz, Rich [<rsalz@akamai.com>](mailto:rsalz@akamai.com)
6 ( 7.9%) | 39144 ( 6.3%) | Keith Moore [<moore@network-heretics.com>](mailto:moore@network-heretics.com)
5 ( 6.6%) | 37813 ( 6.1%) | Lloyd W [<lloyd.wood@yahoo.co.uk>](mailto:lloyd.wood@yahoo.co.uk)
5 ( 6.6%) | 27052 ( 4.3%) | Toerless Eckert [<tte@cs.fau.de>](mailto:tte@cs.fau.de)
4 ( 5.3%) | 59871 ( 9.6%) | Ron Bonica [<rbonica@juniper.net>](mailto:rbonica@juniper.net)
...
