### ISSUE TITLE
update bug reporting links

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/mailarchive#3488]
Currently the bug reporting link points to:

https://tools.ietf.org/tools/ietfdb/newticket (which redirects to: https://trac.ietf.org/trac/ietfdb/newticket, which displays a message suggesting https://github.com/ietf-tools/mailarch). 

It would be better to point directly to the current Github repository.

The email link currently points to django-project@ietf.org. This might also need/benefit from updating to match the flavor used in datatracker, i.e. mailarch-project@ietf.org

**Comment by ghwood** [comment]
Per the recent announcement, the email link should (I believe) instead point to tools-help@ietf.org

**Comment by rpcross** [comment]
Fixed in commit aa34b61
