### ISSUE TITLE
Message-IDs in the archive are erroneously tidied up

### ISSUE THREAD

**Issue by jrlevine** [ietf-tools/mailarchive#3724]
When messages are put in the archive, something tidies up the message-IDs by deleting punctuation characters, e.g.
```
 Message-ID: <CAF4+nEGOK8h3impyQNJ=p57PPb6LsLNqZQroH=AOe7=wzg6+nA@mail.gmail.com>
```
When I reply to a message in the archive:
```
In-Reply-To: <CAF4xnEGOK8h3impyQNJxp57PPb6LsLNqZQroHxAOe7xwzg6xnA@mail.gmail.com>
```
This also affects messages in the web archive, but not those sent by Mailman to list subscribers.
Someone noticed that this screws up threading in replies. The punctuation is valid under RFC 5322 and its predecessors, so it's hard to imagine why it's doing that. But it shouldn't.

**Comment by rpcross** [comment]
Hi John,

When I look up the message id above (with +, =) in the archive, the header looks correct (Show Headers):
https://mailarchive.ietf.org/arch/msg/art/0697b4e4q_U6U0jxwAANhVfNME0/

Can you elaborate on where you are seeing the corrupted id?

Thanks,
Ryan

**Comment by jrlevine** [comment]
Take another look at my note. The actual message ID contained = and + signs that disappeared by the time it was put in the archive. They were present in the copies sent out to the list.
I realized this because I pull messages from the archive via IMAP, and when I reply to them, everyone's message threads are broken because the ID in In-Reply-To was corrupted.

**Comment by rpcross** [comment]
The message file on disk in the archive definitely has the = and + signs, and appears correct in the message view of this Mail Archive application, https://mailarchive.ietf.org/arch/msg/art/0697b4e4q_U6U0jxwAANhVfNME0/. Message ID corruption must be happening further down the chain. Perhaps the IMAP server? Though when I view this message in my Thunderbird client, via IMAP service, the ID also looks correct.

<img width="588" alt="Screenshot 2024-05-10 at 12 02 44 PM" src="https://github.com/ietf-tools/mailarchive/assets/19938627/4d6a2826-874e-4e8e-b53f-3504646e5f42">

**Comment by jrlevine** [comment]
Hm, you're right. Let me see if I can pin it down further.
