### ISSUE TITLE
RFE: https://mailman3.ietf.org/mailman3/lists/ could have a 'last msg sent' column

### ISSUE THREAD

**Issue by moonshiner** [ietf-tools/mailarchive#3758]
https://mailman3.ietf.org/mailman3/lists/ is quite great

Perhaps for lists I am a member of (or owner of) there could be a 'last meesage' field with the timestamp when that was, in some of the old list cases

**Comment by rpcross** [comment]
This repo is specifically for the mailarchive.ietf.org site. For mailman3.ietf.org issues I suggest emailing tools-discuss@ietf.org or tools-help@ietf.org.
