### ISSUE TITLE
Update report bugs "By Email" email address

### ISSUE THREAD

**Issue by kesara** [ietf-tools/mailarchive#3835]
Change report bugs "By Email" link in the footer to `tools-help [𝖺𝗍] ietf.org`.

**Comment by Androideh700** [comment]
- [ ] 

Duplicate of #

**Comment by Androideh700** [comment]
Black:abaut

**Comment by Androideh700** [comment]
#3667

**Comment by Androideh700** [comment]
Write🙋

**Comment by Androideh700** [comment]
[``](url)https://github.com/ietf-tools/mailarchive/issues/3835#issue-2504056168

**Comment by Androideh700** [comment]
<details><summary>Details</summary>
<p>



</p>
</details>
